const FETCH_USERS_LOADING = 'USERS/FETCH_USERS_LOADING';
const FETCH_USERS_ERROR = 'USERS/FETCH_USERS_ERROR';
const FETCH_USERS_SUCCESS = 'USERS/FETCH_USERS_SUCCESS';
const FETCH_NEXT_USERS_SUCCESS = 'USERS/FETCH_NEXT_USERS_SUCCESS';

export default {
  FETCH_USERS_LOADING,
  FETCH_USERS_ERROR,
  FETCH_USERS_SUCCESS,
  FETCH_NEXT_USERS_SUCCESS,
};
